apiVersion: apiextensions.crossplane.io/v1beta1
kind: CompositeResourceDefinition
metadata:
  name: compositek8gbs.k8s.k8gb.io
spec:
  claimNames:
    kind: k8gb
    plural: k8gbs
  group: k8s.k8gb.io
  names:
    kind: CompositeK8gb
    plural: compositek8gbs
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  version:
                    type: string
                    description: "k8gb version"
                  dnsZone:
                    type: string
                    description: "k8gb managed dnz zone"
                  edgeDNSZone:
                    type: string
                    description: "edge DNS Zone in external DNS provider"
                  geoTag:
                    type: string
                    description: "k8gb cluster GeoTag"
                  extGeoTags:
                    type: string
                    description: "comma-separated list of external k8gb geo tags tocommunicate with"
                required:
                  - version
                  - dnsZone
                  - edgeDNSZone
                  - geoTag
                  - extGeoTags
            required:
              - parameters
