# apiVersion: pkg.crossplane.io/v1alpha1
# kind: ControllerConfig
# metadata:
#   name: aws-config
#   labels:
#     app: crossplane-provider-aws
# spec:
#   image: crossplane/provider-aws-controller:v0.20.0
#   args: ["-d"]
# ---
# apiVersion: pkg.crossplane.io/v1
# kind: Provider
# metadata:
#   name: crossplane-provider-aws
# spec:
#   package: crossplane/provider-aws:v0.20.0
#   controllerConfigRef:
#     name: aws-config
#
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: crossplane-provider-helm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: provider-helm-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: crossplane-provider-helm
  namespace: crossplane-system
---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: helm-config
  labels:
    app: crossplane-provider-helm
spec:
  image: crossplane/provider-helm-controller:v0.9.0
  args: ["-d"]
  serviceAccountName: crossplane-provider-helm
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplane-provider-helm
spec:
  package: "crossplane/provider-helm:v0.9.0"
  controllerConfigRef:
    name: helm-config
