apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8gb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  project: default
  source:
    path: k8gb/
    repoURL: https://github.com/somaritane/gitops-sandbox.git
    targetRevision: deploy-providers-with-crossplane
  destination:
    namespace: crossplane-system
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
